backend:
  name: github
  branch: main
  repo: lubojr/decapcms-experiments
  base_url: https://decap-cms-oauth-two.vercel.app
publish_mode: editorial_workflow
site_url: https://decapcms-experiments.vercel.app/
media_folder: docs/media
public_folder: "/media"
search: false
collections:
  - name: "post"  # Used in URLs
    label: "Post"  # Used in the UI
    folder: "docs"  # The path to the post markdown files
    create: true  # Allow users to create new documents
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:  # The fields each document in this collection will have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
        tagname: ''
