backend:
  name: github
  branch: main
  repo: ESA-EarthCODE/open-science-catalog-metadata-testing
  base_url: https://decap-cms-oauth-two.vercel.app
  open_authoring: true
publish_mode: editorial_workflow
site_url: https://decapcms-experiments.vercel.app/
media_folder: docs/media
public_folder: "/media"
search: false
collections:
  - name: "post"  # Used in URLs
    label: "Post"  # Used in the UI
    folder: "docs"  # The path to the post markdown files
    create: true  # Allow users to create new documents
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:  # The fields each document in this collection will have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"} # HAS to be named body BUT can have CUSTOM COMPONENTS
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm',
        }
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
        tagname: ''
      - name: test_widget
        label: Test Widget
        widget: MyCustomTestWidget
      - name: categories
        label: Categories
        widget: CustomCategoriesWidget
        separator: __bla__
      - name: categorieslocal
        label: Categories Local
        widget: categoriesLocal
        separator: "..."
  - name: "staccollections"  # Used in URLs
    label: "STAC Collections"  # Used in the UI
    folder: "stac"  # The path to the post markdown files
    format: "json"
    create: true  # Allow users to create new documents
    slug: "{{slug}}"
    fields:  # The fields each document in this collection will have
      - {label: "ID", name: "id", widget: "string", pattern: ['.{3,}', "Must have at least 3 characters"]}
      - {label: "title", name: "title", widget: "string"}
      - label: "Providers"
        name: "providers" # this is mapped to
        widget: "list"
        collapsed: true
        summary: '{{fields.name}}'
        fields: 
          - { label: Name, name: name, widget: string }
          - { label: Description, name: description, widget: text }
          - { label: Roles, name: roles, widget: list, required: false }
          - { label: Url, name: url, widget: string, required: false }
  - name: "osc-projects"  # Used in URLs
    label: "OSC Projects"  # Used in the UI
    folder: "projects"  # The path to the post markdown files
    format: "json"
    create: true  # Allow users to create new documents
    slug: "{{slug}}"
    fields:  # The fields each document in this collection will have
      - {label: "ID", name: "id", widget: "string", pattern: ['.{3,}', "Must have at least 3 characters"]}
      - {label: "title", name: "title", widget: "string"}
      - { label: Description, name: description, widget: text }
